Model:
  Gaussian_head:
    Name: GuassianHead
    sky_mask: 400.0
    offset_scale: 2.0
    max_scale: 0.1
    max_scale_voxel: 0.2
    pts_range: [-72.0, -72.0, -4.0, 72.0, 72.0, 12.0]
    voxel_size: [0.1, 0.1, 0.2]
    resolution: [518, 350]
    voxel_stream_quantile: 0.6
    voxel_stream_quantile_outview: 0.6
    voxel_stream_opacity_thre: -1
    voxel_stream_inview_num: 300000
    voxel_stream_outview_num: 400000
    sky_gaussian_scale: 1.0
    sky_gaussian_offset: 2.0
    voxel_gs_num: 2


Dataset:
  name: WaymoDataset
  future_num: 1
  frame_num: 5
  resolution: [518, 350]